### ISSUE TITLE
WebView Error Unity AndroidJavaException: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by nice1378** [nhn/gpm.unity#197]
## Service
* WebView

## Version
unity 2020.03.20f

## Summary
Error

## Screenshots
If applicable, add screenshots to help explain your question.

## Additional context
2022-04-19 12:55:35.267 27603 27656 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
2022-04-19 12:55:35.267 27603 27656 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.gpm.webview.GpmWebView.close(Unknown Source:2)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.gpm.webviewplugin.GpmWebViewPlugin.close(Unknown Source:2)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.gpm.webviewplugin.GpmWebViewPlugin.onAsyncMessage(Unknown Source:133)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.gpm.webviewplugin.GpmWebViewPlugin$1.onRequestMessageAsync(Unknown Source:2)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.gpm.communicator.internal.MessageReceiver.onRequestAsync(Unknown Source:38)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at android.os.Looper.loop(Looper.java:223)
2022-04-19 12:55:35.267 27603 27656 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2022-04-19 12:55:35.267 27603 27656 Error Unity Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics

**Comment by taehyeon-nhn** [comment]
Hello. @nice1378 
Thank you for using GPM.

It seems that you need to check the version of the Android SDK that you are currently using.
If you are using Android SDK 28, please update to 30 and confirm.

How to update Android SDK 30.
* Run command prompt as an Administrator.
* cd "C:\Program Files\Unity\Hub\Editor\2020.3.20f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\bin"
* sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"

If you have any questions, please feel free to contact us.
Thanks.

**Comment by taehyeon-nhn** [comment]
Hello. @nice1378
Thank you for using GPM.

I wonder if your problem has been solved.
If you have any questions, please feel free to contact us.

Thanks.

**Comment by nice1378** [comment]
Hello

Updated as said
Same problem occurred
2022-04-30 22:26:39.214 16916 16946 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
2022-04-30 22:26:39.214 16916 16946 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.gpm.webview.GpmWebView.close(Unknown Source:2)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.gpm.webviewplugin.GpmWebViewPlugin.close(Unknown Source:2)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.gpm.webviewplugin.GpmWebViewPlugin.onAsyncMessage(Unknown Source:133)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.gpm.webviewplugin.GpmWebViewPlugin$1.onRequestMessageAsync(Unknown Source:2)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.gpm.communicator.internal.MessageReceiver.onRequestAsync(Unknown Source:38)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at android.os.Looper.loop(Looper.java:223)
2022-04-30 22:26:39.214 16916 16946 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2022-04-30 22:26:39.214 16916 16946 Error Unity Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
2022-04-30 22:26:39.214 16916 16946 Error Unity 	... 11 more
2022-04-30 22:26:39.214 16916 16946 Error Unity   at Unit

**Comment by taehyeon-nhn** [comment]
Hello. @nice1378 

We need more detailed information.

If Android SDK 30 is installed, GPM WebView build should proceed normally.
Please remove the Library folder of project and rebuild it.

If you have proceeded with the [Gradle setting](https://github.com/nhn/gpm.unity/blob/main/docs/WebView/README.en.md#gradle-settings), please remove it and rebuild it.

What settings have you changed in Player Settings and Preferences?

Thanks.

**Comment by taehyeon-nhn** [comment]
Hello. @nice1378 

I wonder if your problem has been solved.
If you have any questions, please feel free to contact us.

Thank you.

**Comment by taehyeon-nhn** [comment]
Hello. @nice1378
Close this issue.

If you have any questions, please feel free to contact us.
Thank you.
